[entryPoints]
    [entryPoints.http]
        address = ":80"
    [entryPoints.traefik]
        address = ":8080"

[entryPoints.http.forwardedHeaders]
    insecure = true

[api]
    dashboard = true

[ping]

[log]
    level = "DEBUG"

[accessLog]
    filePath = "/var/log/traefik/access.log"
    format = "json"

[providers]
    [providers.docker]
        endpoint = "unix:///var/run/docker.sock"
        watch = true
        exposedbydefault = false


